# Generated by Django 4.2.6 on 2023-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='change date'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='change date'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
