# Generated by Django 4.2.6 on 2023-11-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='owner',
        ),
    ]
